/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CSIsatWrap */

#ifndef _Included_CSIsatWrap
#define _Included_CSIsatWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CSIsatWrap
 * Method:    initCaml
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CSIsatWrap_initCaml
  (JNIEnv *, jclass);

/*
 * Class:     CSIsatWrap
 * Method:    interpolateString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CSIsatWrap_interpolateString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
