FROM ocaml/opam:ubuntu-ocaml-4.14
USER opam
WORKDIR /home/opam

COPY --chown=opam:opam mochi.opam .

RUN sudo ln -s /usr/bin/opam-2.1 /usr/local/bin/opam

RUN sudo apt install -y autoconf

RUN opam update && opam install . --deps-only -y -j 1

RUN eval $(opam env) && \
    git clone https://github.com/hopv/horsat2.git horsat2-src && \
    cd horsat2-src && \
    make horsat2 && \
    sudo cp horsat2 /usr/local/bin

RUN rm -r mochi.opam horsat2-src
