#!/bin/sh

TARGET=revision.ml
ECHO=/bin/echo

$ECHO > $TARGET

HASH=`git describe --always --dirty`

if [ $# -eq 1 ]; then
    cat << EOS >> $TARGET
let mochi =
  let s =
    let ver = "%%VERSION%%" in
    if BatString.starts_with ver "%%VERSION%" then
      "$HASH"
    else
      ver
  in
  Some s
EOS
else
    $ECHO 'let mochi = None' >> $TARGET
fi
